### ISSUE TITLE
Terraform crashes when adding new selfips

### ISSUE THREAD

**Issue by lorinwyatt** [terraform-providers/terraform-provider-bigip#220]
When doing a terraform plan for adding new selfips it crashes:
````
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vault_generic_secret.svc-f5-automation: Refreshing state...
bigip_net_selfip.self_ip_1_1_1_1[0]: Refreshing state... [id=/Common/1.1.1.1]
bigip_net_selfip.self_ip_2_2_2_2[0]: Refreshing state... [id=/Common/2.2.22]
bigip_sys_ntp.NTP: Refreshing state... [id=/Common/NTP]
bigip_net_vlan.vlans[0]: Refreshing state... [id=/Common/vlan_111]
bigip_net_vlan.vlans[1]: Refreshing state... [id=/Common/vlan_222]

Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4:
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: goroutine 29 [running]:
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: github.com/terraform-providers/terraform-provider-bigip/bigip.resourceBigipNetSelfIPRead(0xc0001349a0, 0x1c353e0, 0xc00020a550, 0xc0001349a0, 0x0)
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-bigip/bigip/resource_bigip_net_selfip.go:102 +0x622
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: github.com/terraform-providers/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000122b80, 0xc000492690, 0x1c353e0, 0xc00020a550, 0xc0005be270, 0xc000492690, 0x0)
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:447 +0x11c
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: github.com/terraform-providers/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000b2b00, 0x1dfc8a0, 0xc00031d170, 0xc0002b4780, 0xc0000b2b00, 0xc0003d1f80, 0x1af04a0)
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:496 +0x30b
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: github.com/terraform-providers/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x1bf8aa0, 0xc0000b2b00, 0x1dfc8a0, 0xc00031d170, 0xc000492500, 0x0, 0x0, 0x0, 0xc0004cc370, 0xa1)
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:2983 +0x23e
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: github.com/terraform-providers/terraform-provider-bigip/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000578900, 0x1e047c0, 0xc000579080, 0xc00022a100, 0xc00013c510, 0x267bb50, 0x0, 0x0, 0x0)
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-bigip/vendor/google.golang.org/grpc/server.go:971 +0x4a2
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: github.com/terraform-providers/terraform-provider-bigip/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000578900, 0x1e047c0, 0xc000579080, 0xc00022a100, 0x0)
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-bigip/vendor/google.golang.org/grpc/server.go:1250 +0xd61
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: github.com/terraform-providers/terraform-provider-bigip/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000a6480, 0xc000578900, 0x1e047c0, 0xc000579080, 0xc00022a100)
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-bigip/vendor/google.golang.org/grpc/server.go:690 +0x9f
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: created by github.com/terraform-providers/terraform-provider-bigip/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-12-09T13:31:57.064-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-bigip/vendor/google.golang.org/grpc/server.go:688 +0xa1
2019/12/09 13:31:57 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/12/09 13:31:57 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/12/09 13:31:57 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/12/09 13:31:57 [TRACE] [walkRefresh] Exiting eval tree: bigip_net_selfip.self_ip_x_x_x_x[0]
2019/12/09 13:31:57 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_selfip.self_ip_x_x_x_x[0]": visit complete
2019/12/09 13:31:57 [TRACE] [walkRefresh] Exiting eval tree: bigip_net_selfip.self_ip_x_x_x_x[0]
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_selfip.self_ip_x_x_x_x": dynamic subgraph encountered errors
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_selfip.self_ip__x_x_x_x[0]": visit complete
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_selfip.self_ip__x_x_x_x": dynamic subgraph encountered errors
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_selfip.self_ip__x_x_x_x": visit complete
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_selfip.self_ip__x_x_x_x": visit complete
2019/12/09 13:31:57 [TRACE] dag/walk: upstream of "bigip_net_selfip.self_ip_x_x_x_x_f1" errored, so skipping
2019/12/09 13:31:57 [TRACE] dag/walk: upstream of "bigip_net_selfip.self_ip_x_x_x_x_f1" errored, so skipping
2019/12/09 13:31:57 [TRACE] dag/walk: upstream of "provider.bigip.xxxxxxx (close)" errored, so skipping
2019-12-09T13:31:57.066-0700 [DEBUG] plugin: plugin process exited: path=/Users/foo/Documents/repos/tf-base/f5/system/.terraform/plugins/darwin_amd64/terraform-provider-bigip_v1.0.0_x4 pid=21326 error="exit status 2"
2019/12/09 13:31:57 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/12/09 13:31:57 [TRACE] EvalWriteState: writing current state object for bigip_sys_ntp.NTP
2019/12/09 13:31:57 [TRACE] [walkRefresh] Exiting eval tree: bigip_sys_ntp.NTP
2019/12/09 13:31:57 [TRACE] vertex "bigip_sys_ntp.NTP": visit complete
2019/12/09 13:31:57 [TRACE] vertex "bigip_sys_ntp.NTP": dynamic subgraph completed successfully
2019/12/09 13:31:57 [TRACE] vertex "bigip_sys_ntp.NTP": visit complete
2019-12-09T13:31:57.118-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 2019/12/09 13:31:57 [DEBUG] Reading VLAN /Common/vlan_111 Interfaces
2019-12-09T13:31:57.158-0700 [DEBUG] plugin.terraform-provider-bigip_v1.0.0_x4: 2019/12/09 13:31:57 [DEBUG] Reading VLAN /Common/vlan_222 Interfaces
2019/12/09 13:31:57 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/12/09 13:31:57 [TRACE] EvalWriteState: writing current state object for bigip_net_vlan.vlans[0]
2019/12/09 13:31:57 [TRACE] [walkRefresh] Exiting eval tree: bigip_net_vlan.vlans[0]
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_vlan.vlans[0]": visit complete
2019/12/09 13:31:57 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/12/09 13:31:57 [TRACE] EvalWriteState: writing current state object for bigip_net_vlan.vlans[1]
2019/12/09 13:31:57 [TRACE] [walkRefresh] Exiting eval tree: bigip_net_vlan.vlans[1]
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_vlan.vlans[1]": visit complete
2019/12/09 13:31:57 [TRACE] dag/walk: visiting "root"
2019/12/09 13:31:57 [TRACE] vertex "root": starting visit (terraform.graphNodeRoot)
2019/12/09 13:31:57 [TRACE] vertex "root": visit complete
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_vlan.vlans": dynamic subgraph completed successfully
2019/12/09 13:31:57 [TRACE] vertex "bigip_net_vlan.vlans": visit complete
2019/12/09 13:31:57 [TRACE] dag/walk: visiting "provider.bigip (close)"
2019/12/09 13:31:57 [TRACE] vertex "provider.bigip (close)": starting visit (*terraform.graphNodeCloseProvider)
2019/12/09 13:31:57 [TRACE] vertex "provider.bigip (close)": evaluating
2019/12/09 13:31:57 [TRACE] [walkRefresh] Entering eval tree: provider.bigip (close)
2019/12/09 13:31:57 [TRACE] <root>: eval: *terraform.EvalCloseProvider
2019/12/09 13:31:57 [TRACE] GRPCProvider: Close
2019-12-09T13:31:57.201-0700 [DEBUG] plugin: plugin process exited: path=/Users/foo/Documents/repos/tf-base/f5/system/.terraform/plugins/darwin_amd64/terraform-provider-bigip_v1.0.0_x4 pid=21327
2019-12-09T13:31:57.201-0700 [DEBUG] plugin: plugin exited
2019/12/09 13:31:57 [TRACE] [walkRefresh] Exiting eval tree: provider.bigip (close)
2019/12/09 13:31:57 [TRACE] vertex "provider.bigip (close)": visit complete
2019/12/09 13:31:57 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019-12-09T13:31:57.201-0700 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
````

**Comment by papineni87** [comment]
I don't see any crash when i add selfips, can you share the tf files which you are trying to apply it

**Comment by papineni87** [comment]
Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
............................................................................................
bigip_net_vlan.vlan1: Creating...
bigip_net_vlan.vlan2: Creating...
bigip_net_vlan.vlan1: Creation complete after 0s [id=/Common/internal]
bigip_net_vlan.vlan2: Creation complete after 0s [id=/Common/external]
bigip_net_selfip.selfip1: Creating...
bigip_net_selfip.selfip2: Creating...
bigip_net_selfip.selfip1: Creation complete after 0s [id=/Common/internalselfIP]
bigip_net_selfip.selfip2: Creation complete after 0s [id=/Common/externalselfIP]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed

**Comment by focrensh** [comment]
Closing stale issue, please open a new issue if it is still possible to reproduce on newest provider version.
